spring:
  datasource:
    url: jdbc:postgresql://terraform-20221015151538601700000001.cti3rewkpnjv.us-east-1.rds.amazonaws.com/dbpostgresql
    username: postgresql1
    password: foopwdpost!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: kitchen-service
  profiles: qa

server:
  port: 8200

KAFKA_BOOSTRAPADDRESS: kafka-service.default.svc.cluster.local:9192
GROUPID: kitchen

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
