spring:
  datasource:
    url: jdbc:postgresql://terraform-20221019215239791800000001.cti3rewkpnjv.us-east-1.rds.amazonaws.com/postgres
    username: postgresql1
    password: foopwdpost!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: kitchen-service
  profiles: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: 8200

KAFKA_BOOSTRAPADDRESS: kafka-service.default.svc.cluster.local:9192
GROUPID: kitchen

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
      instance-profile: false
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    endpoint:
      tickets:
        url: https://sqs.us-east-1.amazonaws.com/262583979852/ticket_events_jimena.fifo