spring:
  datasource:
    url: jdbc:postgresql://terraform-20221015151538601700000001.cti3rewkpnjv.us-east-1.rds.amazonaws.com/dbpostgresql
    username: postgresql1
    password: foopwdpost!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: order-service
  profiles: qa
  main:
    allow-bean-definition-overriding: true

server:
  port: 8100

KAFKA_BOOSTRAPADDRESS: kafka-service.default.svc.cluster.local:9192
GROUPID: order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
cloud:
  aws:
    credentials:
      access-key: AKIAT2IZZR5GN3UVV3QV
      secret-key: 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
      instance-profile: false
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    endpoint:
      url: https://sqs.us-east-1.amazonaws.com/262583979852/ticket_events.fifo
